export const GET_BIKE_CATEGORY = "GET_BIKE_CATEGORY";
export const GET_BIKE_CATEGORY_SUCCESS = "GET_BIKE_CATEGORY_SUCCESS";
export const GET_BIKE_CATEGORY_ERROR = "GET_BIKE_CATEGORY_ERROR ";
export const GET_LMV_CATEGORY = "GET_LMV_CATEGORY";
export const GET_LMV_CATEGORY_SUCCESS = "GET_LMV_CATEGORY_SUCCESS";
export const GET_LMV_CATEGORY_ERROR = "GET_LMV_CATEGORY_ERROR";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_CURRENT_LOCATION_SUCCESS = "GET_CURRENT_LOCATION_SUCCESS";
export const GET_CURRENT_LOCATION_ERROR = "GET_CURRENT_LOCATION_ERROR";
export const GET_BIKE_PRODUCTS = "GET_BIKE_PRODUCTS";
export const GET_BIKE_PRODUCTS_SUCCESS = "GET_BIKE_PRODUCTS_SUCCESS";
export const GET_BIKE_PRODUCTS_ERROR = "GET_BIKE_PRODUCTS_ERROR";
export const GET_SUBCATEGORY_BASED_BIKE_PRODUCTS =
  "GET_SUBCATEGORY_BASED_BIKE_PRODUCTS";
export const GET_SUBCATEGORY_BASED_BIKE_PRODUCTS_SUCCESS =
  "GET_SUBCATEGORY_BASED_BIKE_PRODUCTS_SUCCESS";
export const GET_SUBCATEGORY_BASED_BIKE_PRODUCTS_ERROR =
  "GET_SUBCATEGORY_BASED_BIKE_PRODUCTS_ERROR";
export const GET_LMV_PRODUCTS = "GET_LMV_PRODUCTS";
export const GET_LMV_PRODUCTS_SUCCESS = "GET_LMV_PRODUCTS_SUCCESS";
export const GET_LMV_PRODUCTS_ERROR = "GET_LMV_PRODUCTS_ERROR";
export const GET_SUBCATEGORY_BASED_LMV_PRODUCTS =
  "GET_SUBCATEGORY_BASED_LMV_PRODUCTS";
export const GET_SUBCATEGORY_BASED_LMV_PRODUCTS_SUCCESS =
  "GET_SUBCATEGORY_BASED_LMV_PRODUCTS_SUCCESS";
export const GET_SUBCATEGORY_BASED_LMV_PRODUCTS_ERROR =
  "GET_SUBCATEGORY_BASED_LMV_PRODUCTS_ERROR";
export const GET_BIKE_PRODUCT_MERCHANTS = "GET_BIKE_PRODUCT_MERCHANTS";
export const GET_BIKE_PRODUCT_MERCHANTS_SUCCESS =
  "GET_BIKE_PRODUCT_MERCHANTS_SUCCESS";
export const GET_BIKE_PRODUCT_MERCHANTS_ERROR =
  "GET_BIKE_PRODUCT_MERCHANTS_ERROR";
export const GET_LMV_PRODUCT_MERCHANTS = "GET_LMV_PRODUCT_MERCHANTS";
export const GET_LMV_PRODUCT_MERCHANTS_SUCCESS =
  "GET_LMV_PRODUCT_MERCHANTS_SUCCESS";
export const GET_LMV_PRODUCT_MERCHANTS_ERROR =
  "GET_LMV_PRODUCT_MERCHANTS_ERROR";
export const GET_BIKE_FEATURE_PRODUCTS = "GET_BIKE_FEATURE_PRODUCTS";
export const GET_BIKE_FEATURE_PRODUCTS_SUCCESS =
  "GET_BIKE_FEATURE_PRODUCTS_SUCCESS";
export const GET_BIKE_FEATURE_PRODUCTS_ERROR =
  "GET_BIKE_FEATURE_PRODUCTS_ERROR";
export const GET_LMV_FEATURE_PRODUCTS = "GET_LMV_FEATURE_PRODUCTS";
export const GET_LMV_FEATURE_PRODUCTS_SUCCESS =
  "GET_LMV_FEATURE_PRODUCTS_SUCCESS";
export const GET_LMV_FEATURE_PRODUCTS_ERROR = "GET_LMV_FEATURE_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
export const GET_PRODUCT_BY_MERCHANT_LMV = "GET_PRODUCT_BY_MERCHANT_LMV";
export const GET_PRODUCT_BY_MERCHANT_LMV_SUCCESS =
  "GET_PRODUCT_BY_MERCHANT_LMV_SUCCESS";
export const GET_PRODUCT_BY_MERCHANT_LMV_ERROR =
  "GET_PRODUCT_BY_MERCHANT_LMV_ERROR";
export const GET_PRODUCT_BY_MERCHANT_BIKE = "GET_PRODUCT_BY_MERCHANT_BIKE";
export const GET_PRODUCT_BY_MERCHANT_BIKE_SUCCESS =
  "GET_PRODUCT_BY_MERCHANT_BIKE_SUCCESS";
export const GET_PRODUCT_BY_MERCHANT_BIKE_ERROR =
  "GET_PRODUCT_BY_MERCHANT_BIKE_ERROR";
export const GET_BIKE_REVIEWS = "GET_BIKE_REVIEWS";
export const GET_BIKE_REVIEWS_SUCCESS = "GET_BIKE_REVIEWS_SUCCESS";
export const GET_BIKE_REVIEWS_ERROR = "GET_BIKE_REVIEWS_ERROR";
export const GET_LMV_REVIEWS = "GET_LMV_REVIEWS";
export const GET_LMV_REVIEWS_SUCCESS = "GET_LMV_REVIEWS_SUCCESS";
export const GET_LMV_REVIEWS_ERROR = "GET_LMV_REVIEWS_ERROR";
export const GET_NEARBY_BIKE_WORKSHOP = "GET_NEARBY_BIKE_WORKSHOP";
export const GET_NEARBY_BIKE_WORKSHOP_SUCCESS =
  "GET_NEARBY_BIKE_WORKSHOP_SUCCESS";
export const GET_NEARBY_BIKE_WORKSHOP_ERROR = "GET_NEARBY_BIKE_WORKSHOP_ERROR";
export const GET_NEARBY_LMV_WORKSHOP = "GET_NEARBY_LMV_WORKSHOP";
export const GET_NEARBY_LMV_WORKSHOP_SUCCESS =
  "GET_NEARBY_LMV_WORKSHOP_SUCCESS";
export const GET_NEARBY_LMV_WORKSHOP_ERROR = "GET_NEARBY_LMV_WORKSHOP_ERROR";
export const GET_BIKE_WORKSHOP = "GET_BIKE_WORKSHOP";
export const GET_BIKE_WORKSHOP_SUCCESS = "GET_BIKE_WORKSHOP_SUCCESS";
export const GET_BIKE_WORKSHOP_ERROR = "GET_BIKE_WORKSHOP_ERROR";
export const GET_LMV_WORKSHOP = "GET_LMV_WORKSHOP";
export const GET_LMV_WORKSHOP_SUCCESS = "GET_LMV_WORKSHOP_SUCCESS";
export const GET_LMV_WORKSHOP_ERROR = "GET_LMV_WORKSHOP_ERROR";
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_ERROR = "GET_BRANDS_ERROR";
export const GET_MODELS = "GET_MODELS";
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_ERROR = "GET_MODELS_ERROR";
export const GET_VEHICLE_TYPE = "GET_VEHICLE_TYPE";
export const GET_VEHICLE_TYPE_SUCCESS = "GET_VEHICLE_TYPE_SUCCESS";
export const GET_VEHICLE_TYPE_ERROR = "GET_VEHICLE_TYPE_ERROR";
export const GET_VEHICLE = "GET_VEHICLE";
export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS";
export const GET_VEHICLE_ERROR = "GET_VEHICLE_ERROR";
export const GET_PARAMETERS = "GET_PARAMETERS";
export const GET_PARAMETERS_SUCCESS = "GET_PARAMETERS_SUCCESS";
export const GET_PARAMETERS_ERROR = "GET_PARAMETERS_ERROR";
export const LOAD_BINDED_PRODUCTS = "LOAD_BINDED_PRODUCTS";
export const FILTERED_PRODUCTS = "FILTERED_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_SORT = "UPDATE_SORT";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const GET_CART = "GET_CART";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const SELECT_ITEM_FROM_ADDONS = "SELECT_ITEM_FROM_ADDONS";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_ERROR = "DELETE_CART_ITEM_ERROR";
export const TOTAL_CART_ITEMS = "TOTAL_CART_ITEMS";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const GET_CUSTOMER_VEHICLE = "GET_CUSTOMER_VEHICLE";
export const GET_CUSTOMER_VEHICLE_SUCCESS = "GET_CUSTOMER_VEHICLE_SUCCESS";
export const GET_CUSTOMER_VEHICLE_ERROR = "GET_CUSTOMER_VEHICLE_ERROR";
export const CREATE_CUSTOMER_VEHICLE = "CREATE_CUSTOMER_VEHICLE";
export const CREATE_CUSTOMER_VEHICLE_SUCCESS =
  "CREATE_CUSTOMER_VEHICLE_SUCCESS";
export const CREATE_CUSTOMER_VEHICLE_ERROR = "CREATE_CUSTOMER_VEHICLE_ERROR";
export const UPDATE_CUSTOMER_VEHICLE = "UPDATE_CUSTOMER_VEHICLE";
export const UPDATE_CUSTOMER_VEHICLE_SUCCESS =
  "UPDATE_CUSTOMER_VEHICLE_SUCCESS";
export const UPDATE_CUSTOMER_VEHICLE_ERROR = "UPDATE_CUSTOMER_VEHICLE_ERROR";
export const DELETE_CUSTOMER_VEHICLE = "DELETE_CUSTOMER_VEHICLE";
export const DELETE_CUSTOMER_VEHICLE_SUCCESS =
  "DELETE_CUSTOMER_VEHICLE_SUCCESS";
export const DELETE_CUSTOMER_VEHICLE_ERROR = "DELETE_CUSTOMER_VEHICLE_ERROR";
export const CUSTOMER_VEHICLE_STATUS_UPDATE = "CUSTOMER_VEHICLE_STATUS_UPDATE";
export const CUSTOMER_VEHICLE_STATUS_UPDATE_SUCCESS =
  "CUSTOMER_VEHICLE_STATUS_UPDATE_SUCCESS";
export const CUSTOMER_VEHICLE_STATUS_UPDATE_ERROR =
  "CUSTOMER_VEHICLE_STATUS_UPDATE_ERROR";
export const GET_BIKE_ORDERS = "GET_BIKE_ORDERS";
export const GET_BIKE_ORDERS_SUCCESS = "GET_BIKE_ORDERS_SUCCESS";
export const GET_BIKE_ORDERS_ERROR = "GET_BIKE_ORDERS_ERROR";
export const GET_LMV_ORDERS = "GET_LMV_ORDERS";
export const GET_LMV_ORDERS_SUCCESS = "GET_LMV_ORDERS_SUCCESS";
export const GET_LMV_ORDERS_ERROR = "GET_LMV_ORDERS_ERROR";
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_ERROR = "GET_SINGLE_ORDER_ERROR";
